# Generated by Django 2.2.5 on 2019-10-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Start description value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
