# Generated by Django 2.2.5 on 2019-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20191015_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
