# Generated by Django 2.2.7 on 2019-11-10 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_reservation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x0411F970> <django.db.models.query_utils.DeferredAttribute object at 0x0411F990>'), related_name='id_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_reservation',
            field=models.TextField(),
        ),
    ]
