# Generated by Django 2.2.7 on 2019-11-20 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0008_auto_20191110_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('capacityAdults', models.IntegerField()),
                ('capacityKids', models.IntegerField()),
                ('marriage', models.BooleanField(default=False)),
                ('apartment', models.BooleanField(default=False)),
                ('multiplier', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x034DF970> <django.db.models.query_utils.DeferredAttribute object at 0x034DF990>'), related_name='id_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
