# Generated by Django 2.2.5 on 2021-06-15 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0010_auto_20191120_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.IntegerField()),
                ('country_code', models.TextField()),
                ('country', models.TextField()),
                ('who_region', models.TextField()),
                ('new_cases', models.IntegerField()),
                ('cumulative_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x03CEB6F0> <django.db.models.query_utils.DeferredAttribute object at 0x03CEB710>'), related_name='id_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
