# Generated by Django 2.2.5 on 2021-06-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0011_auto_20210615_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
