# Generated by Django 2.2.5 on 2021-06-15 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphs', '0012_auto_20210615_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_Cd', models.TextField()),
                ('valid_from', models.IntegerField()),
                ('valid_to', models.IntegerField()),
                ('function', models.TextField()),
                ('fit_perctentage', models.TextField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
